<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>QueryGuard.AspNetCore.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/QueryGuard.AspNetCore/QueryGuard.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
