<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>QueryGuard.SampleTests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../QueryGuard.SampleApi/QueryGuard.SampleApi.csproj" />
    <ProjectReference Include="../../src/QueryGuard.Testing/QueryGuard.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

</Project>
